
const gender = [
  "Female",
  "Male",
  "Agender",
  "Androgyne",
  "Androgynes",
  "Androgynous",
  "Asexual",
  "Bigender",
  "Cis",
  "Cis Female",
  "Cis Male",
  "Cis Man",
  "Cis Woman",
  "Cisgender",
  "Cisgender Female",
  "Cisgender Male",
  "Cisgender Man",
  "Cisgender Woman",
  "Female to Male",
  "FTM",
  "Gender Fluid",
  "Gender Nonconforming",
  "Gender Questioning",
  "Gender Variant",
  "Genderqueer",
  "Intersex",
  "Male to Female",
  "MTF",
  "Neither",
  "Neutrois",
  "Non-binary",
  "Other",
  "Pangender",
  "Trans",
  "Trans Female",
  "Trans Male",
  "Trans Man",
  "Trans Person",
  "Trans*Female",
  "Trans*Male",
  "Trans*Man",
  "Trans*Person",
  "Trans*Woman",
  "Transexual",
  "Transexual Female",
  "Transexual Male",
  "Transexual Man",
  "Transexual Person",
  "Transexual Woman",
  "Transgender Female",
  "Transgender Person",
  "Transmasculine",
  "Two-spirit",
  "Asexual",
  "F2M",
  "Gender neutral",
  "Hermaphrodite",
  "Intersex man",
  "Intersex person",
  "Intersex woman",
  "Man",
  "M2F",
  "Polygender",
  "T* man",
  "T* woman",
  "Two* person",
  "Two-spirit person",
  "Woman"
]

module.exports = gender;